. .bashrc

export PIP_DOWNLOAD_CACHE=/tmp/pip
export DJANGO_SETTINGS_MODULE=settings
export PYTHONPATH=$PYTHONPATH:~/sites/yoyoyo/checkouts/yoyoyo/readtheyoyoyo
export EDITOR=vim

. sites/yoyoyo/bin/activate

cd ~/sites/yoyoyo/


alias chk='cd /home/yoyoyo/sites/yoyoyo/checkouts/yoyoyo'
alias run='cd /home/yoyoyo/sites/yoyoyo/run'

