export EDITOR=vim

function psg {
    ps auxww | grep --color=always $* | grep -v grep | sed -e 's/  */ /g' | cut -d' ' -f 2,11-
}

alias ls='ls -h'
alias l='ls'
alias du='du -sh'
alias rmpyc='find . -name "*.pyc" -exec rm {} \;'

cd /home/coolname/app && source /home/coolname/env/bin/activate
